title: "Milad Pourdanandeh"
author: "Milad Pourdanandeh"
description: "Milad Pourdanandeh<br>PhD student<br>Department of Marine Sciences<br>University of Gothenburg"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%Y-%m-%d"

# Layout
show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true              # use a dark header

# Menu
navigation:
  - {title: '<i class="fa-solid fa-file-lines"></i> Blog', file: "blog.md"}
  - {title: '<i class="fa-brands fa-google-scholar"></i> Scholar', url: "https://scholar.google.se/citations?hl=en&user=nySwgx0AAAAJ"}
  - {title: "UoG", url: "https://www.gu.se/en/about/find-staff/miladpourdanandeh"}
  - {title: "Lab", url: "https://pelagial.se/"}
  - {title: '<i class="fa-brands fa-researchgate"></i>', url: "https://www.researchgate.net/profile/Milad-Pourdanandeh"}

external:
  - {title: "", icon: "fa-solid fa-envelope", url: "mailto:milad.pourdanandeh@gu.se"}
  - {title: "", icon: "fa-brands fa-github", url: "https://github.com/pourmilad"}
  - {title: "", icon: "fa-solid fa-mosquito", url: "https://bsky.app/profile/pourmilad.bsky.social"}
  
  
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
