title: "Milad Pourdanandeh"
author: "Milad Pourdanandeh"
description: "Department of Marine Sciences<br>University of Gothenburg"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%Y-%m-%d"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Blog", icon: file-lines, file: "blog.md"}
  - {title: "Scholar", icon: google-scholar, url: "https://scholar.google.se/citations?hl=en&user=nySwgx0AAAAJ"}
  - {title: "UoG", url: "https://www.gu.se/en/about/find-staff/miladpourdanandeh"}
  - {title: "Lab", icon: flask, url: "https://pelagial.se/"}
  - {title: "About", file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:milad.pourdanandeh@gu.se"}
  - {title: Github, icon: github, url: "https://github.com/pourmilad"}
  - {title: Subscribe, icon: bluesky, url: "https://bsky.app/profile/pourmilad.bsky.social"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
